apiVersion: v1
kind: Service
metadata:
  name: crypto-api-service
spec:
  type: NodePort
  selector:
    app: crypto-api
  ports:
    - port: 5000
      nodePort: 30001  # Dostęp do API przez port 30001